import {
  GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_CONSUMER_SURFACE,
  GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_PROFILE_BOUNDARY,
  GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_PROFILE_KIND,
  GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_PROFILE_SCHEMA_ID,
  GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_PROFILE_STAGE,
  GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_PROFILE_VERSION,
} from "./governanceCaseReviewDecisionCurrentSelectionProfile.mjs";
import {
  GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_CONTRACT_BOUNDARY,
  GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_CONTRACT_KIND,
  GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_CONTRACT_VERSION,
} from "./governanceCaseReviewDecisionCurrentSelectionContract.mjs";

export const GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_VERSION =
  "v1";
export const GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_STABILITY =
  "stable";
export const GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_CONSUMER_TIER =
  "governance_case_review_decision_current_selection_surface";
export const GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_ARTIFACT_ORDER =
  Object.freeze(["governance_case_review_decision_current_selection"]);
export const GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_META_EXPORTS =
  Object.freeze([
    "GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_VERSION",
    "GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_STABILITY",
    "GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_CONSUMER_TIER",
    "GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_ARTIFACT_ORDER",
    "GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_META_EXPORTS",
    "GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_STABLE_EXPORT_SET",
    "GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_MAP",
    "getGovernanceCaseReviewDecisionCurrentSelectionSurfaceEntry",
    "listGovernanceCaseReviewDecisionCurrentSelectionSurfaceEntries",
    "exportGovernanceCaseReviewDecisionCurrentSelectionSurface",
  ]);
export const GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_STABLE_EXPORT_SET =
  Object.freeze([
    ...GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_META_EXPORTS,
  ]);
export const GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_MAP =
  Object.freeze({
    governance_case_review_decision_current_selection: Object.freeze({
      artifact_id: "governance_case_review_decision_current_selection",
      consumer_surface:
        GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_CONSUMER_SURFACE,
      contract: Object.freeze({
        kind: GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_PROFILE_KIND,
        version:
          GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_PROFILE_VERSION,
        schema_id:
          GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_PROFILE_SCHEMA_ID,
        stage: GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_PROFILE_STAGE,
        boundary:
          GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_PROFILE_BOUNDARY,
      }),
      boundary_contract: Object.freeze({
        kind: GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_CONTRACT_KIND,
        version:
          GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_CONTRACT_VERSION,
        boundary:
          GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_CONTRACT_BOUNDARY,
      }),
      supporting_artifact_only: true,
      recommendation_only: true,
      additive_only: true,
      current_selection_supported: true,
      deterministic: true,
      executing: false,
    }),
  });

export function getGovernanceCaseReviewDecisionCurrentSelectionSurfaceEntry(
  artifactId
) {
  return (
    GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_MAP[artifactId] ??
    null
  );
}

export function listGovernanceCaseReviewDecisionCurrentSelectionSurfaceEntries() {
  return GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_ARTIFACT_ORDER.map(
    (artifactId) =>
      getGovernanceCaseReviewDecisionCurrentSelectionSurfaceEntry(artifactId)
  );
}

export function exportGovernanceCaseReviewDecisionCurrentSelectionSurface() {
  return GOVERNANCE_CASE_REVIEW_DECISION_CURRENT_SELECTION_SURFACE_MAP;
}
