export const GUARD_REASON_CATEGORIES = {
  AUTHORITY: "authority",
  SCOPE: "scope",
  VERIFICATION: "verification",
  RELEASE_ROLLBACK: "release_rollback",
  TOOL_ACTION: "tool_action",
  DATA_SECURITY: "data_security",
  EVIDENCE_INTEGRITY: "evidence_integrity",
  DEPENDENCY_CHANGE: "dependency_change",
  HUMAN_REVIEW: "human_review",
} as const;

export type GuardReasonCategory =
  (typeof GUARD_REASON_CATEGORIES)[keyof typeof GUARD_REASON_CATEGORIES];

export const GUARD_REASON_SEVERITY_HINTS = {
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high",
  CRITICAL: "critical",
} as const;

export type GuardReasonSeverityHint =
  (typeof GUARD_REASON_SEVERITY_HINTS)[keyof typeof GUARD_REASON_SEVERITY_HINTS];

export const GUARD_REASON_LATER_USED_BY = {
  EVIDENCE_COVERAGE: "evidence_coverage",
  RISK_SUMMARY: "risk_summary",
  REVIEW_REQUIREMENTS: "review_requirements",
  RECEIPTS: "receipts",
  REPORTS: "reports",
  NEXT_ACTIONS: "next_actions",
} as const;

export type GuardReasonLaterUsedBy =
  (typeof GUARD_REASON_LATER_USED_BY)[keyof typeof GUARD_REASON_LATER_USED_BY];

export const GUARD_REASON_CODES = {
  MISSING_AUTHORITY: "MISSING_AUTHORITY",
  DECLARED_AUTHORITY_ONLY: "DECLARED_AUTHORITY_ONLY",
  AUTHORITY_OUT_OF_SCOPE: "AUTHORITY_OUT_OF_SCOPE",
  REVIEWER_MISSING: "REVIEWER_MISSING",
  OWNER_MISSING: "OWNER_MISSING",
  TIME_WINDOW_MISSING: "TIME_WINDOW_MISSING",
  TIME_WINDOW_EXPIRED: "TIME_WINDOW_EXPIRED",
  OUT_OF_SCOPE_ACTION: "OUT_OF_SCOPE_ACTION",
  OUT_OF_SCOPE_RESOURCE: "OUT_OF_SCOPE_RESOURCE",
  PROTECTED_RESOURCE_TOUCHED: "PROTECTED_RESOURCE_TOUCHED",
  UNDECLARED_FILE_CHANGE: "UNDECLARED_FILE_CHANGE",
  SCOPE_TOO_BROAD: "SCOPE_TOO_BROAD",
  SCOPE_INCOMPLETE: "SCOPE_INCOMPLETE",
  INSUFFICIENT_VERIFICATION: "INSUFFICIENT_VERIFICATION",
  TESTS_NOT_RUN: "TESTS_NOT_RUN",
  TESTS_FAILED: "TESTS_FAILED",
  BUILD_NOT_RUN: "BUILD_NOT_RUN",
  BUILD_FAILED: "BUILD_FAILED",
  STATIC_ANALYSIS_NOT_RUN: "STATIC_ANALYSIS_NOT_RUN",
  SECURITY_SCAN_NOT_RUN: "SECURITY_SCAN_NOT_RUN",
  MANUAL_REVIEW_MISSING: "MANUAL_REVIEW_MISSING",
  ROLLBACK_MISSING: "ROLLBACK_MISSING",
  ROLLBACK_UNVERIFIED: "ROLLBACK_UNVERIFIED",
  RELEASE_TARGET_UNCLEAR: "RELEASE_TARGET_UNCLEAR",
  PRODUCTION_ENVIRONMENT_UNVERIFIED: "PRODUCTION_ENVIRONMENT_UNVERIFIED",
  BLOCKED_ACTION_PRESENT: "BLOCKED_ACTION_PRESENT",
  DESTRUCTIVE_COMMAND_ATTEMPTED: "DESTRUCTIVE_COMMAND_ATTEMPTED",
  SECRET_ACCESS_ATTEMPTED: "SECRET_ACCESS_ATTEMPTED",
  NETWORK_ACCESS_ATTEMPTED: "NETWORK_ACCESS_ATTEMPTED",
  UNSAFE_GIT_OPERATION: "UNSAFE_GIT_OPERATION",
  TOOL_OUTPUT_MISSING: "TOOL_OUTPUT_MISSING",
  COMMAND_RESULT_MISSING: "COMMAND_RESULT_MISSING",
  HIGH_RISK_DATA: "HIGH_RISK_DATA",
  DATA_SENSITIVITY_UNKNOWN: "DATA_SENSITIVITY_UNKNOWN",
  CREDENTIAL_RISK: "CREDENTIAL_RISK",
  EXFILTRATION_RISK: "EXFILTRATION_RISK",
  SECURITY_PATCH_SCOPE_UNCLEAR: "SECURITY_PATCH_SCOPE_UNCLEAR",
  CYBER_AUTHORIZATION_REQUIRED: "CYBER_AUTHORIZATION_REQUIRED",
  EVIDENCE_INCOMPLETE: "EVIDENCE_INCOMPLETE",
  MANIFEST_INCOMPLETE: "MANIFEST_INCOMPLETE",
  ARTIFACT_MISSING: "ARTIFACT_MISSING",
  ARTIFACT_HASH_MISSING: "ARTIFACT_HASH_MISSING",
  ARTIFACT_REF_UNRESOLVED: "ARTIFACT_REF_UNRESOLVED",
  PROVENANCE_MISSING: "PROVENANCE_MISSING",
  PRODUCER_IDENTITY_UNKNOWN: "PRODUCER_IDENTITY_UNKNOWN",
  NON_DETERMINISTIC_PRODUCER: "NON_DETERMINISTIC_PRODUCER",
  DEPENDENCY_CHANGE_DETECTED: "DEPENDENCY_CHANGE_DETECTED",
  BREAKING_CHANGE_UNVERIFIED: "BREAKING_CHANGE_UNVERIFIED",
  LOCKFILE_CHANGED: "LOCKFILE_CHANGED",
  MIGRATION_NOT_DOCUMENTED: "MIGRATION_NOT_DOCUMENTED",
  PUBLIC_API_CHANGE_UNVERIFIED: "PUBLIC_API_CHANGE_UNVERIFIED",
  HUMAN_REVIEW_REQUIRED: "HUMAN_REVIEW_REQUIRED",
  SECURITY_REVIEW_REQUIRED: "SECURITY_REVIEW_REQUIRED",
  OWNER_REVIEW_REQUIRED: "OWNER_REVIEW_REQUIRED",
  RELEASE_REVIEW_REQUIRED: "RELEASE_REVIEW_REQUIRED",
  CUSTOMER_REVIEW_REQUIRED: "CUSTOMER_REVIEW_REQUIRED",
} as const;

export type GuardReasonCode =
  (typeof GUARD_REASON_CODES)[keyof typeof GUARD_REASON_CODES];

export interface GuardReasonCodeDefinition {
  code: GuardReasonCode;
  category: GuardReasonCategory;
  severity_hint: GuardReasonSeverityHint;
  description: string;
  later_used_by: readonly GuardReasonLaterUsedBy[];
}

function defineReasonCode(
  code: GuardReasonCode,
  category: GuardReasonCategory,
  severityHint: GuardReasonSeverityHint,
  description: string,
  laterUsedBy: readonly GuardReasonLaterUsedBy[],
): GuardReasonCodeDefinition {
  return {
    code,
    category,
    severity_hint: severityHint,
    description,
    later_used_by: laterUsedBy,
  };
}

const COVERAGE_AND_REPORTING = [
  GUARD_REASON_LATER_USED_BY.EVIDENCE_COVERAGE,
  GUARD_REASON_LATER_USED_BY.RISK_SUMMARY,
  GUARD_REASON_LATER_USED_BY.RECEIPTS,
  GUARD_REASON_LATER_USED_BY.REPORTS,
] as const;

const REVIEW_AND_REPORTING = [
  GUARD_REASON_LATER_USED_BY.RISK_SUMMARY,
  GUARD_REASON_LATER_USED_BY.REVIEW_REQUIREMENTS,
  GUARD_REASON_LATER_USED_BY.RECEIPTS,
  GUARD_REASON_LATER_USED_BY.REPORTS,
  GUARD_REASON_LATER_USED_BY.NEXT_ACTIONS,
] as const;

const NEXT_ACTIONS_AND_REPORTING = [
  GUARD_REASON_LATER_USED_BY.RISK_SUMMARY,
  GUARD_REASON_LATER_USED_BY.RECEIPTS,
  GUARD_REASON_LATER_USED_BY.REPORTS,
  GUARD_REASON_LATER_USED_BY.NEXT_ACTIONS,
] as const;

export const GUARD_REASON_CODE_DEFINITIONS: Record<
  GuardReasonCode,
  GuardReasonCodeDefinition
> = {
  MISSING_AUTHORITY: defineReasonCode(
    GUARD_REASON_CODES.MISSING_AUTHORITY,
    GUARD_REASON_CATEGORIES.AUTHORITY,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Submitted evidence does not include authority material needed for governance interpretation.",
    REVIEW_AND_REPORTING,
  ),
  DECLARED_AUTHORITY_ONLY: defineReasonCode(
    GUARD_REASON_CODES.DECLARED_AUTHORITY_ONLY,
    GUARD_REASON_CATEGORIES.AUTHORITY,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Authority is declared in the pack but lacks stronger supporting evidence.",
    REVIEW_AND_REPORTING,
  ),
  AUTHORITY_OUT_OF_SCOPE: defineReasonCode(
    GUARD_REASON_CODES.AUTHORITY_OUT_OF_SCOPE,
    GUARD_REASON_CATEGORIES.AUTHORITY,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Submitted authority material does not cover the recorded workflow scope.",
    REVIEW_AND_REPORTING,
  ),
  REVIEWER_MISSING: defineReasonCode(
    GUARD_REASON_CODES.REVIEWER_MISSING,
    GUARD_REASON_CATEGORIES.AUTHORITY,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Expected reviewer context is absent from submitted evidence.",
    REVIEW_AND_REPORTING,
  ),
  OWNER_MISSING: defineReasonCode(
    GUARD_REASON_CODES.OWNER_MISSING,
    GUARD_REASON_CATEGORIES.AUTHORITY,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Expected ownership context is absent from submitted evidence.",
    REVIEW_AND_REPORTING,
  ),
  TIME_WINDOW_MISSING: defineReasonCode(
    GUARD_REASON_CODES.TIME_WINDOW_MISSING,
    GUARD_REASON_CATEGORIES.AUTHORITY,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Authority evidence does not include a bounded time window.",
    REVIEW_AND_REPORTING,
  ),
  TIME_WINDOW_EXPIRED: defineReasonCode(
    GUARD_REASON_CODES.TIME_WINDOW_EXPIRED,
    GUARD_REASON_CATEGORIES.AUTHORITY,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Authority time window is present but appears no longer current.",
    REVIEW_AND_REPORTING,
  ),
  OUT_OF_SCOPE_ACTION: defineReasonCode(
    GUARD_REASON_CODES.OUT_OF_SCOPE_ACTION,
    GUARD_REASON_CATEGORIES.SCOPE,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "An action recorded in the pack exceeds the declared scope.",
    REVIEW_AND_REPORTING,
  ),
  OUT_OF_SCOPE_RESOURCE: defineReasonCode(
    GUARD_REASON_CODES.OUT_OF_SCOPE_RESOURCE,
    GUARD_REASON_CATEGORIES.SCOPE,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "A touched resource exceeds the declared workflow scope.",
    REVIEW_AND_REPORTING,
  ),
  PROTECTED_RESOURCE_TOUCHED: defineReasonCode(
    GUARD_REASON_CODES.PROTECTED_RESOURCE_TOUCHED,
    GUARD_REASON_CATEGORIES.SCOPE,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Evidence indicates contact with a protected resource.",
    REVIEW_AND_REPORTING,
  ),
  UNDECLARED_FILE_CHANGE: defineReasonCode(
    GUARD_REASON_CODES.UNDECLARED_FILE_CHANGE,
    GUARD_REASON_CATEGORIES.SCOPE,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Changed files appear outside the declared file list or declared limits.",
    REVIEW_AND_REPORTING,
  ),
  SCOPE_TOO_BROAD: defineReasonCode(
    GUARD_REASON_CODES.SCOPE_TOO_BROAD,
    GUARD_REASON_CATEGORIES.SCOPE,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Submitted scope is broader than the expected governance boundary.",
    REVIEW_AND_REPORTING,
  ),
  SCOPE_INCOMPLETE: defineReasonCode(
    GUARD_REASON_CODES.SCOPE_INCOMPLETE,
    GUARD_REASON_CATEGORIES.SCOPE,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Submitted scope material is incomplete for later interpretation.",
    REVIEW_AND_REPORTING,
  ),
  INSUFFICIENT_VERIFICATION: defineReasonCode(
    GUARD_REASON_CODES.INSUFFICIENT_VERIFICATION,
    GUARD_REASON_CATEGORIES.VERIFICATION,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Verification material is present but not strong enough for the recorded workflow.",
    COVERAGE_AND_REPORTING,
  ),
  TESTS_NOT_RUN: defineReasonCode(
    GUARD_REASON_CODES.TESTS_NOT_RUN,
    GUARD_REASON_CATEGORIES.VERIFICATION,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Evidence indicates test activity did not occur.",
    COVERAGE_AND_REPORTING,
  ),
  TESTS_FAILED: defineReasonCode(
    GUARD_REASON_CODES.TESTS_FAILED,
    GUARD_REASON_CATEGORIES.VERIFICATION,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Evidence indicates test activity ended unsuccessfully.",
    COVERAGE_AND_REPORTING,
  ),
  BUILD_NOT_RUN: defineReasonCode(
    GUARD_REASON_CODES.BUILD_NOT_RUN,
    GUARD_REASON_CATEGORIES.VERIFICATION,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Evidence indicates build verification did not occur.",
    COVERAGE_AND_REPORTING,
  ),
  BUILD_FAILED: defineReasonCode(
    GUARD_REASON_CODES.BUILD_FAILED,
    GUARD_REASON_CATEGORIES.VERIFICATION,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Evidence indicates build verification ended unsuccessfully.",
    COVERAGE_AND_REPORTING,
  ),
  STATIC_ANALYSIS_NOT_RUN: defineReasonCode(
    GUARD_REASON_CODES.STATIC_ANALYSIS_NOT_RUN,
    GUARD_REASON_CATEGORIES.VERIFICATION,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Expected static analysis evidence is absent.",
    COVERAGE_AND_REPORTING,
  ),
  SECURITY_SCAN_NOT_RUN: defineReasonCode(
    GUARD_REASON_CODES.SECURITY_SCAN_NOT_RUN,
    GUARD_REASON_CATEGORIES.VERIFICATION,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Expected security scan evidence is absent.",
    COVERAGE_AND_REPORTING,
  ),
  MANUAL_REVIEW_MISSING: defineReasonCode(
    GUARD_REASON_CODES.MANUAL_REVIEW_MISSING,
    GUARD_REASON_CATEGORIES.VERIFICATION,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Expected human review evidence is absent.",
    REVIEW_AND_REPORTING,
  ),
  ROLLBACK_MISSING: defineReasonCode(
    GUARD_REASON_CODES.ROLLBACK_MISSING,
    GUARD_REASON_CATEGORIES.RELEASE_ROLLBACK,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Rollback evidence is absent for a release-oriented workflow.",
    REVIEW_AND_REPORTING,
  ),
  ROLLBACK_UNVERIFIED: defineReasonCode(
    GUARD_REASON_CODES.ROLLBACK_UNVERIFIED,
    GUARD_REASON_CATEGORIES.RELEASE_ROLLBACK,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Rollback material is present but not verified strongly enough.",
    REVIEW_AND_REPORTING,
  ),
  RELEASE_TARGET_UNCLEAR: defineReasonCode(
    GUARD_REASON_CODES.RELEASE_TARGET_UNCLEAR,
    GUARD_REASON_CATEGORIES.RELEASE_ROLLBACK,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Release target details are incomplete or unclear.",
    REVIEW_AND_REPORTING,
  ),
  PRODUCTION_ENVIRONMENT_UNVERIFIED: defineReasonCode(
    GUARD_REASON_CODES.PRODUCTION_ENVIRONMENT_UNVERIFIED,
    GUARD_REASON_CATEGORIES.RELEASE_ROLLBACK,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Production environment material is not sufficiently verified.",
    REVIEW_AND_REPORTING,
  ),
  BLOCKED_ACTION_PRESENT: defineReasonCode(
    GUARD_REASON_CODES.BLOCKED_ACTION_PRESENT,
    GUARD_REASON_CATEGORIES.TOOL_ACTION,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "A halted action appears in submitted evidence.",
    NEXT_ACTIONS_AND_REPORTING,
  ),
  DESTRUCTIVE_COMMAND_ATTEMPTED: defineReasonCode(
    GUARD_REASON_CODES.DESTRUCTIVE_COMMAND_ATTEMPTED,
    GUARD_REASON_CATEGORIES.TOOL_ACTION,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Evidence indicates an attempted destructive command.",
    NEXT_ACTIONS_AND_REPORTING,
  ),
  SECRET_ACCESS_ATTEMPTED: defineReasonCode(
    GUARD_REASON_CODES.SECRET_ACCESS_ATTEMPTED,
    GUARD_REASON_CATEGORIES.TOOL_ACTION,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Evidence indicates an attempted secret-access operation.",
    NEXT_ACTIONS_AND_REPORTING,
  ),
  NETWORK_ACCESS_ATTEMPTED: defineReasonCode(
    GUARD_REASON_CODES.NETWORK_ACCESS_ATTEMPTED,
    GUARD_REASON_CATEGORIES.TOOL_ACTION,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Evidence indicates an attempted network operation.",
    NEXT_ACTIONS_AND_REPORTING,
  ),
  UNSAFE_GIT_OPERATION: defineReasonCode(
    GUARD_REASON_CODES.UNSAFE_GIT_OPERATION,
    GUARD_REASON_CATEGORIES.TOOL_ACTION,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Evidence indicates a Git operation with elevated safety concern.",
    NEXT_ACTIONS_AND_REPORTING,
  ),
  TOOL_OUTPUT_MISSING: defineReasonCode(
    GUARD_REASON_CODES.TOOL_OUTPUT_MISSING,
    GUARD_REASON_CATEGORIES.TOOL_ACTION,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "A recorded tool interaction lacks expected output material.",
    COVERAGE_AND_REPORTING,
  ),
  COMMAND_RESULT_MISSING: defineReasonCode(
    GUARD_REASON_CODES.COMMAND_RESULT_MISSING,
    GUARD_REASON_CATEGORIES.TOOL_ACTION,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "A recorded command interaction lacks expected result material.",
    COVERAGE_AND_REPORTING,
  ),
  HIGH_RISK_DATA: defineReasonCode(
    GUARD_REASON_CODES.HIGH_RISK_DATA,
    GUARD_REASON_CATEGORIES.DATA_SECURITY,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Submitted evidence indicates interaction with high-risk data.",
    REVIEW_AND_REPORTING,
  ),
  DATA_SENSITIVITY_UNKNOWN: defineReasonCode(
    GUARD_REASON_CODES.DATA_SENSITIVITY_UNKNOWN,
    GUARD_REASON_CATEGORIES.DATA_SECURITY,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Data sensitivity context is absent or unclear.",
    REVIEW_AND_REPORTING,
  ),
  CREDENTIAL_RISK: defineReasonCode(
    GUARD_REASON_CODES.CREDENTIAL_RISK,
    GUARD_REASON_CATEGORIES.DATA_SECURITY,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Evidence indicates credential-handling risk.",
    REVIEW_AND_REPORTING,
  ),
  EXFILTRATION_RISK: defineReasonCode(
    GUARD_REASON_CODES.EXFILTRATION_RISK,
    GUARD_REASON_CATEGORIES.DATA_SECURITY,
    GUARD_REASON_SEVERITY_HINTS.CRITICAL,
    "Evidence indicates possible exfiltration risk.",
    REVIEW_AND_REPORTING,
  ),
  SECURITY_PATCH_SCOPE_UNCLEAR: defineReasonCode(
    GUARD_REASON_CODES.SECURITY_PATCH_SCOPE_UNCLEAR,
    GUARD_REASON_CATEGORIES.DATA_SECURITY,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Security patch evidence does not define a clear remediation scope.",
    REVIEW_AND_REPORTING,
  ),
  CYBER_AUTHORIZATION_REQUIRED: defineReasonCode(
    GUARD_REASON_CODES.CYBER_AUTHORIZATION_REQUIRED,
    GUARD_REASON_CATEGORIES.DATA_SECURITY,
    GUARD_REASON_SEVERITY_HINTS.CRITICAL,
    "Cyber-oriented workflow evidence calls for stronger authorization material.",
    REVIEW_AND_REPORTING,
  ),
  EVIDENCE_INCOMPLETE: defineReasonCode(
    GUARD_REASON_CODES.EVIDENCE_INCOMPLETE,
    GUARD_REASON_CATEGORIES.EVIDENCE_INTEGRITY,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Submitted evidence is structurally present but incomplete for stronger interpretation.",
    COVERAGE_AND_REPORTING,
  ),
  MANIFEST_INCOMPLETE: defineReasonCode(
    GUARD_REASON_CODES.MANIFEST_INCOMPLETE,
    GUARD_REASON_CATEGORIES.EVIDENCE_INTEGRITY,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Manifest completeness indicates omitted or partial evidence inventory.",
    COVERAGE_AND_REPORTING,
  ),
  ARTIFACT_MISSING: defineReasonCode(
    GUARD_REASON_CODES.ARTIFACT_MISSING,
    GUARD_REASON_CATEGORIES.EVIDENCE_INTEGRITY,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "An expected artifact is absent from submitted evidence.",
    COVERAGE_AND_REPORTING,
  ),
  ARTIFACT_HASH_MISSING: defineReasonCode(
    GUARD_REASON_CODES.ARTIFACT_HASH_MISSING,
    GUARD_REASON_CATEGORIES.EVIDENCE_INTEGRITY,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "An artifact reference is present without stable hash material.",
    COVERAGE_AND_REPORTING,
  ),
  ARTIFACT_REF_UNRESOLVED: defineReasonCode(
    GUARD_REASON_CODES.ARTIFACT_REF_UNRESOLVED,
    GUARD_REASON_CATEGORIES.EVIDENCE_INTEGRITY,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "An artifact reference cannot be resolved within submitted evidence.",
    COVERAGE_AND_REPORTING,
  ),
  PROVENANCE_MISSING: defineReasonCode(
    GUARD_REASON_CODES.PROVENANCE_MISSING,
    GUARD_REASON_CATEGORIES.EVIDENCE_INTEGRITY,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Provenance material is absent from submitted evidence.",
    COVERAGE_AND_REPORTING,
  ),
  PRODUCER_IDENTITY_UNKNOWN: defineReasonCode(
    GUARD_REASON_CODES.PRODUCER_IDENTITY_UNKNOWN,
    GUARD_REASON_CATEGORIES.EVIDENCE_INTEGRITY,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Producer identity is absent or cannot be established from submitted evidence.",
    COVERAGE_AND_REPORTING,
  ),
  NON_DETERMINISTIC_PRODUCER: defineReasonCode(
    GUARD_REASON_CODES.NON_DETERMINISTIC_PRODUCER,
    GUARD_REASON_CATEGORIES.EVIDENCE_INTEGRITY,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Producer metadata indicates evidence generation may not be deterministic.",
    COVERAGE_AND_REPORTING,
  ),
  DEPENDENCY_CHANGE_DETECTED: defineReasonCode(
    GUARD_REASON_CODES.DEPENDENCY_CHANGE_DETECTED,
    GUARD_REASON_CATEGORIES.DEPENDENCY_CHANGE,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Evidence indicates a dependency-oriented software change.",
    REVIEW_AND_REPORTING,
  ),
  BREAKING_CHANGE_UNVERIFIED: defineReasonCode(
    GUARD_REASON_CODES.BREAKING_CHANGE_UNVERIFIED,
    GUARD_REASON_CATEGORIES.DEPENDENCY_CHANGE,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Evidence suggests possible breaking change impact without strong verification.",
    REVIEW_AND_REPORTING,
  ),
  LOCKFILE_CHANGED: defineReasonCode(
    GUARD_REASON_CODES.LOCKFILE_CHANGED,
    GUARD_REASON_CATEGORIES.DEPENDENCY_CHANGE,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Evidence indicates lockfile material changed during the workflow.",
    REVIEW_AND_REPORTING,
  ),
  MIGRATION_NOT_DOCUMENTED: defineReasonCode(
    GUARD_REASON_CODES.MIGRATION_NOT_DOCUMENTED,
    GUARD_REASON_CATEGORIES.DEPENDENCY_CHANGE,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Migration-oriented evidence is expected but absent.",
    REVIEW_AND_REPORTING,
  ),
  PUBLIC_API_CHANGE_UNVERIFIED: defineReasonCode(
    GUARD_REASON_CODES.PUBLIC_API_CHANGE_UNVERIFIED,
    GUARD_REASON_CATEGORIES.DEPENDENCY_CHANGE,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Evidence indicates public API change without strong verification.",
    REVIEW_AND_REPORTING,
  ),
  HUMAN_REVIEW_REQUIRED: defineReasonCode(
    GUARD_REASON_CODES.HUMAN_REVIEW_REQUIRED,
    GUARD_REASON_CATEGORIES.HUMAN_REVIEW,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Later governance flow may call for human review.",
    REVIEW_AND_REPORTING,
  ),
  SECURITY_REVIEW_REQUIRED: defineReasonCode(
    GUARD_REASON_CODES.SECURITY_REVIEW_REQUIRED,
    GUARD_REASON_CATEGORIES.HUMAN_REVIEW,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Later governance flow may call for security-oriented review.",
    REVIEW_AND_REPORTING,
  ),
  OWNER_REVIEW_REQUIRED: defineReasonCode(
    GUARD_REASON_CODES.OWNER_REVIEW_REQUIRED,
    GUARD_REASON_CATEGORIES.HUMAN_REVIEW,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Later governance flow may call for owner review.",
    REVIEW_AND_REPORTING,
  ),
  RELEASE_REVIEW_REQUIRED: defineReasonCode(
    GUARD_REASON_CODES.RELEASE_REVIEW_REQUIRED,
    GUARD_REASON_CATEGORIES.HUMAN_REVIEW,
    GUARD_REASON_SEVERITY_HINTS.HIGH,
    "Later governance flow may call for release review.",
    REVIEW_AND_REPORTING,
  ),
  CUSTOMER_REVIEW_REQUIRED: defineReasonCode(
    GUARD_REASON_CODES.CUSTOMER_REVIEW_REQUIRED,
    GUARD_REASON_CATEGORIES.HUMAN_REVIEW,
    GUARD_REASON_SEVERITY_HINTS.MEDIUM,
    "Later governance flow may call for customer-facing review.",
    REVIEW_AND_REPORTING,
  ),
};

export const GUARD_REASON_CODE_LIST = Object.values(
  GUARD_REASON_CODES,
) as readonly GuardReasonCode[];
